// POSTS
export const RECEIVE_POSTS = 'RECEIVE_POSTS'
export const DELETE_POST = 'DELETE_POST'
export const EDIT_POST = 'EDIT_POST'
export const ADD_POST = 'ADD_POST'

// CATEGORIES
export const RECEIVE_CATEGORIES = 'RECEIVE_CATEGORIES'

// COMMENTS
export const RECEIVE_COMMENTS = 'RECEIVE_COMMENTS'